export const FETCH_ITEMDATA_START = 'FETCH_ITEMDATA_START';
export const FETCH_ITEMDATA_SUCCESS = 'FETCH_ITEMDATA_SUCCESS';
export const FETCH_ITEMDATA_ERROR = 'FETCH_ITEMDATA_ERROR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const INCREMENT_CART = 'INCREMENT_CART';
export const MODIFY_CART = 'MODIFY_CART';